---
title: "Article 1"
description: |
  A mother mouse’s gut microbes help wire her pup’s brain
author:
  - name: Anne-Charlotte Vranckx
    url: {https://github.com/AnneCharlotteVranckx}
date: "`r Sys.Date()`"
categories:
  - "English for Science"
preview: mouse.jpg
output:
  distill::distill_article:
    self_contained: false
---
# Source, date & words
***

I decided to choose an [article](https://www.sciencenews.org/article/mother-mouse-gut-microbes-microbiome-pup-brain) from *ScienceNews*.
I consulted the page on Tuesday, 25th September 2020.
The article has been published on Wednesday, 23th 2020.

**Word count** :

- 498 in summmary
- 213 in analyzes

# Summary
***
The microbes living in a female mouse’s gut help to wire the offspring’s brain. The study explains how a mother’s microbiome can develop long-term outcomes in her offspring.
In the past, scientists found connections between the microbiome of a mouse mother and her offsprings. But there is a problem : the animals were put under stress or were ill. Helen Vuong and her colleagues (UCLA) wanted to know the impact of a mother's microbial mix on her offspring's brains.

They saw that specific microbes and small molecules (named metabolites) from the mother's microbiome have a big influence on the development brain of the fetus. Metabolites act on the development of the pup's brain by affecting the growth of axons.

H. Vuong and her team decided to take the fetuses from 3 types of pregnant mice: 
- pregnant mice with regular gut bugs
- pregnant mice without microbes
- pregnant mice without gut bacteria (they used antibitoics)

For the two very last groups, fetuses suffered from shorter and fewer axons extending from the  brain's relay station to the cortex. The result is that these offsprings will be less sensory sensitive because these connections are important for processing sensory information.
They were less sensitive to touch than mice from mothers with regular gut bugs.
The mice from the 2 last groups took sensory tests: "They took longer to notice a small piece of tape stuck to one of their paws".
If we give *Clostridia bacteria* (common gut microbes) to female without regular gut bugs, the offsprings develop a normal brain and a normal conduct.The absence of these bacteria is linked to some non-transferable conditions (as food allergies)

They discovered that small molecules are made by microorganisms in the gut intervene for this effect. They also discovered that certain metabolites present in the mother's blood are linked to the blood and the brain of their offsprings.
We can make a little conclusion by saying that the mother shares her metabolites (from the gut) with her pups.
If we give supplements of those metabolites to pregnant mice without a regular microbiome, the pups develop a normal conduct.

It is important to mention that we don't know exactly how gut microbes and metabolites intervene in the development of the human brain.
Nevertheless, we know that a mouse mother suffers from a deficit of gut bugs or metabolite during the pregnancy will have pups who will suffer from developmental problems concerning brain and behavior. If we know the deficit quickly, we can give complements to the pregnant mouse.

A microbiologist (Carolina Tropini) says that it is important to know if these deficits have also consequences on human (and leading to long-term medical problems).
Researchers have to compare the benefits of antibiotics (which are on short-term) to the potential risks (which can be on long-term). They also have to discover if therapies and solutions exist for pregnant women who need to take antibiotics.

# Vocabulary
***
| Word from the text | Definition | Synonyms |
|-----|-----|-----|
| gut | the stomach or belly | stomach |
| to wire | provide, fasten, or reinforce with wires | to reinforce |
| offspring | an animal's young | progeny, children |
| microbiome | a community of microorganisms that inhabit a particular environment and especially the collection of microorganisms living in or on a animal | / |
| metabolites | a substance formed in or necessary for metabolism | / |
|bugs|a harmful microorganism, typically a bacterium|bacteria|
|paw|an animal's foot having claws and pads|pad|
|axone|threadlike signal-transmitters of nerve cells|/|

# Analysis Table
***
| **Basic article informations**      | **Informations** |
| ----- | ----- |
|**Researchers** | Carolyn Wilke (who wrote the article), Helen Vuong and her colleagues, Cathryn Nagler (not involved in the study), University of Chicago, Carolina Tropini |
| **Published in**  | in ScienceNews / on September 23, 2020  
| **General topic** | link betwen mom’s gut microbes and her baby’s sensory connection |
| **Procedure/what was examinated?** |  How microbes living in the gut of a normal female can develop long-term outcomes on her offspring ? **=>** they uses 3 types of pregnant mice (with & without microbes and using antibiotics) **=>** Giving Clostridia bacteria to female without regular bacteria in their gut **=>** give complements of metabolites and bacteria to pregant mice |
| **Conclusion/discoveries** | Influence of small microbes and metabolites on offsprings **=>** impact on axons **=>** fetuses from mothers without regular gut bugs **=>** suffered from shorter and fewer axons extending from the  brain's relay station to the cortex **=>** less sensory sensitive to touch **=>** fetuses from mother without a regular gut bugs but received Clostridia has a normal brain and behavior development **=>** absence of these bacteria is linked to some non-transfereble conditions. They discovered that small molecules and metabolites  from the mother are linked to the blood and brain of offsprings **=>** the pups from pregnant mice which received complements develop a normal conduct |
| **Remaining questions**| What is the impact of gut bugs on human fetuses ? How gut microbes and metabolites intervene in the development of human brain ? |
